#!/bin/bash

# the environment variable ${TRAVIS_PULL_REQUEST} is set
# to "false" when the build is for a normal branch commit.
# When the build is for a pull request, it will contain the
# pull request’s number.
if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
  mkdir $HOME/.bintray/
  FILE=$HOME/.bintray/.credentials
cat <<EOF >$FILE
realm = Bintray API Realm
host = api.bintray.com
user = ${BINTRAY_USER}
password = ${BINTRAY_TOKEN}
EOF

  git config --global user.email "oss@travis-ci.org"
  git config --global user.name "travis-ci"
  git config credential.helper "store --file=.git/credentials"
  echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
  git fetch -q --unshallow
  git checkout -qf ${TRAVIS_BRANCH}

  sbt ++$TRAVIS_SCALA_VERSION "release with-defaults"
else
  # for pull requests only do tests
  sbt ++$TRAVIS_SCALA_VERSION test
fi
